api.sandbox.ebay.com:
  appid: <Davidsol-TeamNort-SBX-938876c40-4d9db6df>
  certid: <SBX-38876c403bc5-ebcc-4a26-bcc9-5b18>
  devid: <7d9f71d8-f186-4b70-8980-9bd5123f5bd2>
  redirecturi: <David_solowitz-Davidsol-TeamNo-rwpdhijqd>